<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUPdtItT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUPdtItT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUPdtItT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUPdtItT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUPdtItT\App_KernelDevDebugContainer([
    'container.build_hash' => 'UPdtItT',
    'container.build_id' => 'a909c3b2',
    'container.build_time' => 1730380112,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUPdtItT');
