<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFWrblhA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFWrblhA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFWrblhA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFWrblhA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFWrblhA\App_KernelDevDebugContainer([
    'container.build_hash' => 'FWrblhA',
    'container.build_id' => '0eb8862f',
    'container.build_time' => 1759309292,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFWrblhA');
