<?php

namespace ContainerFWrblhA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpenseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ExpenseController' shared autowired service.
     *
     * @return \App\Controller\ExpenseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ExpenseController.php';

        $container->services['App\\Controller\\ExpenseController'] = $instance = new \App\Controller\ExpenseController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\ExpenseController', $container));

        return $instance;
    }
}
