version: '3.8'

services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    environment:
      KEY: supersecretkey
      SECRET: anothersecretkey
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus
    depends_on:
      - postgres
  
  frontend:
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
